name: Deploy Project
on: push
jobs:
  deploy:
    runs-on: ubuntu/latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run:  npm ci
      - name: Lint
        run:  npm run lint
      - name: Test
        run:  npm run test
      - name: Build project
        run:  npm run build 
      - name: Deployment
        run:  echo "Deploying to cloud...."