name: Demo Github Actions
on: 
  pull_request:
    branches: 
      - master
  push:
    branches:
      - dev
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: linting
      run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:   
    - name: Get the code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Build code
      run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:   
    - name: Get the code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Build code
      run: npm run build
    - name: Deploy code
      run: echo "Deploying...."


